name: 'My Composite Action'
description: 'A composite GitHub Action that runs multiple shell commands'

inputs:
  name:
    description: 'Your name'
    required: true
    default: 'World'

runs:
  using: 'composite'
  steps:
    - name: Run multiple commands
      run: ./script.sh
      shell: bash
      with:
        name: ${{ inputs.name }}

